chatbot/urls.py
from django.contrib import admin
from django.urls import path
from django.views.generic import TemplateView

from .views import HarvestEmails, Home, CreateAnswer, Chat

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('answer', CreateAnswer.as_view(), name='create_answer'),
    path('emails/', HarvestEmails.as_view(), name='harvest_emails'),
    path('chat/<pk>/', Chat.as_view(), name='chat'),
]

chatbot/models.py
import uuid as uuid_lib

from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver

from django_chatbot.storage_backends import PublicMediaStorage

from allauth.socialaccount.models import SocialToken, SocialApp
from allauth.socialaccount.signals import social_account_added
from google.oauth2.credentials import Credentials
from googleapiclient.discovery import build

class UserProfile(models.Model):

    uuid = models.UUIDField(db_index=True, 
        default=uuid_lib.uuid4, editable=False)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    description = models.CharField(max_length=255, blank=True,
        default='a friendly AI assistant')
    prompt = models.TextField(blank=True)

    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            UserProfile.objects.create(user=instance)
    
    @receiver(social_account_added)
    def account_added(request, sociallogin, **kwargs):
        app = SocialApp.objects.get(provider='google')
        token = SocialToken.objects.get(account__user=request.user)
        credentials = Credentials(
            token=token.token,
            refresh_token=token.token_secret,
            client_id=app.client_id,
            client_secret=app.secret,
        )
        service = build('gmail', 'v1', credentials=credentials)
        emails = service.users().messages().list(userId='saraabi@gmail.com', q='is:unread').execute()
        print(emails)
        return emails

    def __str__(self):
        return self.user.get_full_name()

    def get_display_name(self):
        return self.user.get_full_name()

    def build_prompt(self):
        prompt = """The following is a conversation with an \
            AI assistant.\nHuman: Who are you?
            AI: I am {0}""".format(self.description)
        for answer in self.answer_set.all():
            prompt += """
                Human: {0}
                AI: {1}""".format(answer.question.name,
                    answer.text)
        return prompt


class Question(models.Model):

    name = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    user = models.ForeignKey(UserProfile, 
        on_delete=models.SET_NULL, blank=True, null=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    is_training = models.BooleanField(default=False)

    class Meta:
        ordering = ('timestamp',)

    def __str__(self):
        return self.name

class Answer(models.Model):

    question = models.ForeignKey(Question, 
        on_delete=models.CASCADE)
    text = models.TextField(blank=True)
    user = models.ForeignKey(UserProfile, 
        on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return 'Response to {}'.format(self.question.name)

    class Meta:
        ordering = ('timestamp',) 

class Thread(models.Model):

    gmail_id = models.CharField(max_length=255, blank=True)
    subject = models.CharField(max_length=255, blank=True)

    def __str__(self):
        return self.subject
    
    def get_length(self):
        return self.email_set.count()
    
    def store_emails(self, email_dict):
        email = Email.objects.create(

        )

class Email(models.Model):

    gmail_id = models.CharField(max_length=255)
    _from = models.EmailField(max_length=255, blank=True)
    to = models.EmailField(max_length=255, blank=True)
    subject = models.CharField(max_length=255, blank=True)
    body = models.TextField(blank=True)
    timestamp = models.DateTimeField(blank=True, null=True)
    thread = models.ForeignKey(Thread, on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return self.subject

templates/base.html
<!DOCTYPE html>
{% load socialaccount %}
<html lang="en">
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>ChatBot</title>
        <!-- <meta name="Description" content="">
        <meta charset="UTF-8">
        <meta property="og:title" content="Samer's Chatbot Client" />
        <meta property="og:url" content="https://www.araborganizing.org" />
        <meta property="og:image" content="" />
        <meta property="og:type" content="website" />
        <meta property="og:description" content="" /> -->
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Lora:ital,wght@0,400;0,600;1,400;1,600&family=Montserrat:wght@200;400;600&display=swap" rel="stylesheet">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
        <script src="https://code.jquery.com/jquery-3.6.1.min.js" integrity="sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ=" crossorigin="anonymous"></script>
        <script src="https://kit.fontawesome.com/226fadf0e2.js" crossorigin="anonymous"></script>
        <style>
            nav, h1, h3, h4, footer p {
                font-family: 'Montserrat', sans-serif;
            }
            nav i {
                color: #101010;
            }
            h1 {
                font-size: 4rem;
            }
            h3 {
                color: #640012;
                font-size: 2.5rem;
                letter-spacing: 0.2rem;
            }
            h4 {
                font-size: 2rem;
                letter-spacing: 0.1rem;
            }
            p {
                color: #010101;
                font-family: 'Lora', serif;
                font-size: 1.5rem;
            }
            a {
                transition: all 0.2s;
            }
            a:hover {
                color: #EE2A35;
                opacity: 0.7;
            }
            .Messages {
                position: fixed;
                width: 100%;
                z-index: 100000;
            }
            .Message {
                position: absolute;
                top: 0;
                left: 50%;
                width: 500px;
                margin-left: -250px;
                padding: 10px;
                text-align: center;
                border-radius: 0 0 4px 4px;
            }
            .Messages .error {
                color: #fff;
                background-color: #F78181;
            }

            .Messages .success {
                color: #FFFFFF;
                background-color: #26B99A;
                cursor: pointer;
            }

            .Messages.hide {
                display: none;
            }
            .btn-primary {
                background-color: #640012;
                border-color: #640012;
            }
            .btn-primary:hover {
                background-color: #EE2A35;
                border-color: #EE2A35;
            }
            .bg-black {
                background-color: #101010 !important;
            }
            .Vision {
                font-family: 'Lora', serif;
                font-size: 2.3rem;
                line-height: 3.5rem;
            }
            .nav-link {
                font-size: 1.3rem;
                text-transform: uppercase;
            }
            .OvalButton {
                border-top-left-radius: 300px;
                border-top-right-radius: 300px;
                border-bottom-right-radius: 300px;
                border-bottom-left-radius: 300px;
                padding: 1.2rem;
                font-size: 1rem;
                font-weight: 600;
            }
            .DonateButton {
                border: 2px solid #010101;
                color: #010101;
                text-decoration: none;
                text-transform: uppercase;
                transition: all 0.3s;
                vertical-align: super;
            }
                .DonateButton:hover {
                    color: #FFFFFF;
                    background-color: #010101;
                }
                DonateButton--wide {
                    padding: 1.2rem 2rem;
                }
            .SectionButton {
                border: 2px solid #FFFFFF;
                color: #FFFFFF;
                text-align: center;
                width: 50%;
                margin: 1rem auto;
                transition: 0.2s;
            }
                .SectionButton:hover {
                    background-color: #FFFFFF;
                    color: #010101;
                    opacity: 0.7;
                }
            .Hero {
                background: linear-gradient( rgba(0, 0, 0, 0.2), rgba(0, 0, 0, 0.4) ), url(https://asfour.s3.us-west-1.amazonaws.com/media/public/dabke_highrez.jpeg);
                min-height: 600px;
                /* background-attachment: fixed; */
                background-position: center;
                background-repeat: no-repeat;
                background-size: cover;
                position: relative;
            }
                .Hero p {
                    position: absolute;
                    bottom: 2%;
                    right: 2%;
                    font-family: 'Montserrat', sans-serif;
                    font-size: 14px;
                    opacity: 0.7;
                }
            .Hero-about {
                background: linear-gradient( rgba(0, 0, 0, 0.2), rgba(0, 0, 0, 0.4) ), url(https://asfour.s3.us-west-1.amazonaws.com/media/public/staff.jpg);
                background-position: center;
                min-height: 600px;
                /* background-attachment: fixed; */
                background-repeat: no-repeat;
                background-size: cover;
                position: relative;
            }
                .Hero-about h1 {
                    position: absolute;
                    top: 50%;
                    left: 50%;
                    transform: translate(-50%, -50%);
                }
                .Hero-about p {
                    position: absolute;
                    bottom: 3%;
                    right: 3%;
                    font-family: 'Montserrat', sans-serif;
                    font-size: 14px;
                }
            .Hero-learn {
                background: linear-gradient( rgba(0, 0, 0, 0.2), rgba(0, 0, 0, 0.4) ), url(https://asfour.s3.us-west-1.amazonaws.com/media/public/endurbanshield-11.jpg);
                background-repeat: no-repeat;
                background-size: cover;
                background-position-y: 28%;
                position: relative;
            }
            .PhotoSection {
                border-radius: 4px;
                height: 450px;
                width: 340px;
                text-decoration: none;
            }
                .PhotoSection-text {
                    color: #FFFFFF;
                    font-family: 'Montserrat', sans-serif;
                    font-size: 1.8rem;
                    text-align: center;
                    text-transform: uppercase;
                }
                .SectionOne {
                    background: linear-gradient( rgba(238, 42, 53, 0.5), rgba(238, 42, 53, 0.5) ), url(https://asfour.s3.us-west-1.amazonaws.com/media/public/urbanshield.jpeg);
                    background-position: center;
                    background-repeat: no-repeat;
                    background-size: cover;
                }
                .SectionTwo {
                    background: linear-gradient( rgba(0, 0, 0, 0.8), rgba(255, 255, 255, 0.5) ), url(https://asfour.s3.us-west-1.amazonaws.com/media/public/SF_Eid_2022-62.jpeg);
                    background-repeat: no-repeat;
                    background-size: cover;
                }
                .SectionThree {
                    background: linear-gradient( rgba(0, 151, 54, 0.6), rgba(0, 151, 54, 0.6) ), url(https://asfour.s3.us-west-1.amazonaws.com/media/public/Nakba_day-78.jpeg);
                    background-repeat: no-repeat;
                    background-size: cover;
                }
            .SectionTitle {
                text-transform: uppercase;
            }
            .Bios h5 {
                font-size: 1.5rem;
            }
            .Bios h6 {
                font-size: 1.25rem;
            }
            .Bios p {
                font-size: 1.2rem;
            }
            .Gradient {
                background: linear-gradient(to right, rgba(238, 42, 53, 1), rgba(100, 0, 18, 1), rgba(100, 0, 18, 1), rgba(100, 0, 18, 1), rgba(238, 42, 53, 1))
            }
                .Gradient h4 {
                    font-weight: 200;
                }
            footer a {
                color: #FFFFFF;
                text-decoration: none;
            }
            .FooterSections h3 {
                color: #FFFFFF;
            }
            .FooterSection {
                max-width:300px;
            }
            @media only screen and (max-width: 800px) {
            }
        </style>
    </head>
    <body>
        {% if messages %}
            <div class="Messages">
                {% for message in messages %}
                <div id="id_message{{ message.id }}" class="Message {{ message.tags }}">{{ message }}</div>
                {% endfor %}
            </div>
        {% endif %}
        <nav class="navbar navbar-expand-lg sticky-top bg-white">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'home' %}"><img src="" height=90></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto me-auto mb-2 mb-lg-0">
                      <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% provider_login_url 'google' %}">Connect Gmail</a>
                      </li>
                      <!-- <li class="nav-item">
                        <a class="nav-link">About Us</a>
                      </li> -->
                      <!-- <li class="nav-item">
                        <a class="nav-link" href="https://us10.list-manage.com/contact-form?u=40bbc5d297cb5db1fd1a5ca21&form_id=1cea505ec15293ac4c9e82fcdee69646">Contact Us</a>
                      </li> -->
                      <!-- <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                          Dropdown
                        </a>
                        <ul class="dropdown-menu">
                          <li><a class="dropdown-item" href="#">Action</a></li>
                          <li><a class="dropdown-item" href="#">Another action</a></li>
                          <li><hr class="dropdown-divider"></li>
                          <li><a class="dropdown-item" href="#">Something else here</a></li>
                        </ul>
                      </li> -->
                    </ul>
                   
                </div>
            </div>
        </nav>
        <main>
            <div class="mx-auto w-75">
            {% block content %}
            {% endblock %}
            </div>
        </main>
        <footer class="bg-black py-5">

        </footer>
    </body>
    <script>
        $('.Message').click(function() {
            $('.Message').fadeOut("slow");
        });
        $(document).ready(function() {
            // messages timeout for 5 sec
            setTimeout(function() {
                $('.Message').fadeOut('slow');
            }, 3000); // <-- time in milliseconds, 1000 =  1 sec

        });
    </script>
    {% block javascript %}
    {% endblock %}
</html>

templates/harvest_emails.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<h1>ChatBot</h1>
<div class="card mx-auto mt-5 p-4">
    {% for thread in emails %}
    <table class="table">
        <thead>
          <tr>
            <th scope="col"></th>
            <th scope="col">Date</th>
            <th scope="col">From</th>
            <th scope="col">Subject</th>
          </tr>
        </thead>
        <tbody>
            {% for email in thread %}
          <tr>
            <th scope="row"><input type="checkbox" value="{{ email.id }}"></th>
            <td>{{ email.date }}</td>
            <td>{{ email.from }}</td>
            <td>{{ email.subject }}</td>
          </tr>
          {% endfor %}
        </tbody>
    </table>
    {% endfor %}

</div>

{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<h1>ChatBot</h1>
<div class="card mx-auto mt-5 p-4">
    <form class="Form mt-4" action="" method="POST">
        {% csrf_token %}
        <p>Write a one sentence description of your chatbot's personality</p>
        <div class="form-group">
        <label>My AI assistant is:</label>
        <input class="textinput textInput form-control" type="text" name="description" {% if userprofile.description %}value="{{ userprofile.description }}"{% endif %}>
        <input type="submit" value="Submit" class="btn btn-primary">
    </form>
</div>
<p>Conversation</p>
{% for question in userprofile.question_set.all %}
    <p><em>{{ question.timestamp }}</em> Question: {{ question.name }}</p>
    {% for answer in question.answer_set.all %}
    <p><em>{{ answer.timestamp }}</em> Answer: {{ answer.text }}</p>
    {% endfor %}
{% endfor %}
<form class="Form mt-4" action="{% url 'chat' pk=userprofile.id %}" method="POST">
    {% csrf_token %}
    
    <div class="form-group">
    <input class="textinput textInput form-control"  type="text" name="question">
    <input type="submit" value="Submit" class="btn btn-primary">
</form>
{% endblock %}